const mongoose = require('mongoose');
const DB = require("../models");


mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/MM"
);

const playerSeed = [
    {
        image: "https://www.instagram.com/p/CHrI_J2sAcB/",
        name: "Terrell Lewis",
        school: "Los Angeles Rams",
        position: "DE",
        link: "https://www.instagram.com/_real24/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/B22JA18H_nJ/",
        name: "Jaylen Twyman",
        school: "Pitt",
        position: "DL",
        link: "https://www.instagram.com/p/B22JA18H_nJ/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/CKFqdGnsaZy/",
        name: "Tyree Johnson",
        school: "Texa A&M",
        position: "DB",
        link: "https://www.instagram.com/tyguwwop/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/CHn4CP2MRtB/",
        name: "Corey Brown Jr.",
        school: "VSU",
        position: "DT",
        link: "https://www.instagram.com/c.b.__2/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/CGgDMGxMFxE/",
        name: "Jamree Kromah",
        school: "Rutgers University",
        position: "DE",
        link: "https://www.instagram.com/jamreekromah/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/BnDMNH-g1X6/",
        name: "Jamal Jones",
        school: "VU",
        position: "DE\OLB",
        link: "https://www.instagram.com/bigmal_50/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/BqDzbofljL-/",
        name: "Eric Mckan III",
        school: "Cal State D.C.",
        position: "RB",
        link: "https://www.instagram.com/its.babydd/",
        sport: "Football",
    },
    {
        image: "",
        name: "Cameron Lomax",
        school: "West Virginia Wesleyan College",
        position: "DB",
        link: "https://www.instagram.com/cammbandz/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/B_svyIwgKog/",
        name: "Amanni Stewart",
        school: "TBD",
        position: "QB",
        link: "https://www.instagram.com/1_manni_1/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/B3m6Azfn0kf/",
        name: "Christian Braswell",
        school: "Temple University",
        position: "CB",
        link: "https://www.instagram.com/cb2____/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/B4vKbDRn3gt/",
        name: "Josh Wallace",
        school: "UMass",
        position: "CB",
        link: "https://www.instagram.com/josh.w12/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/Bh-X28zF2cZ/",
        name: "Jermaine Waller",
        school: "VT",
        position: "DB",
        link: "https://www.instagram.com/jwaller_1/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/B0IAAjogeMU/",
        name: "Derrick Newman Jr",
        school: "Berry College",
        position: "",
        link: "https://www.instagram.com/dnewman_5/",
        sport: "Baseball",
    },
    {
        image: "https://www.instagram.com/p/B5wXLlOHnmH/",
        name: "Domo",
        school: "ODU",
        position: "QB",
        link: "https://www.instagram.com/domo1x/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/CLNxGE4nq_G/",
        name: "Lani Foster",
        school: " URI",
        position: "WR",
        link: "https://www.instagram.com/lanifoster_/",
        sport: "Football",
    },
    
    {
        image: "https://www.instagram.com/p/CJ6ooBosvqN/",
        name: "Zack Isaac",
        school: "TBD",
        position: "LB",
        link: "https://www.instagram.com/mmzack_bi4q/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/CK2Q2fLAd4c/",
        name: "Marcus Smith II",
        school: "Seattle Seahawks",
        position: "DL",
        link: "https://www.instagram.com/moneymarc91/",
        sport: "Football",
    },
    {
        image: "https://www.instagram.com/p/B3uEOJEHxKy/",
        name: "Marky Mark",
        school: "Haven",
        position: "PG",
        link: "https://www.instagram.com/markym4rkk/",
        sport: "Basketball",
    },
    {
        image: "https://www.instagram.com/p/B8sTpq4hWe_/",
        name: "DJ",
        school: "TBD",
        position: "Hurderls / RB",
        link: "https://www.instagram.com/davidwarmington_/",
        sport: "TF / Football",
    },
    {
        image: "https://www.instagram.com/p/B61XCLtgwri/",
        name: "Olusegun Oluwatimi",
        school: "UV",
        position: "OL",
        link: "https://www.instagram.com/big_olu55/",
        sport: "Football",
    },
]